"use strict";
exports.__esModule = true;
var namespace_1 = require("./namespace");
exports.namespace = namespace_1.namespace;
var _a = namespace_1.namespace(Symbol('my-async-store')), add = _a.add, del = _a.del, has = _a.has, wait = _a.wait, clear = _a.clear, size = _a.size, store = _a.store;
exports.add = add;
exports.del = del;
exports.has = has;
exports.wait = wait;
exports.clear = clear;
exports.size = size;
exports.store = store;
